[target.aarch64-unknown-linux-gnu]
image = "xcb/arm"

[target.arm-unknown-linux-musleabihf]
image = "xcb/arm"

[target.x86_64-unknown-linux-musl]
image = "xcb/arm"

[target.i686-unknown-linux-gnu]
image = "xcb/arm"